

FROM python:3.13.4-alpine3.22

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo de requisitos e instala dependências
COPY requirements.txt .

# Usamos --no-cache-dir para evitar o cache do pip, reduzindo da
# imagem
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação para o diretório de trabalho
# do contêiner
COPY . .

# Expõe a parte que a aplicação FastAPI ira rodar (o padrão é 8000)
EXPOSE 8000

# Comando para rodar a aplicação usando uvicorn. O host 0.0.0.0 permite
# que a aplicação seja acessivel externamente ao contéiner 
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]